<a href="https://colab.research.google.com/github/Vigneshburra/Homewrok_10/blob/main/Homework_10.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [2]:
import pandas as pd
import numpy as np

In [34]:
df=pd.read_csv("/content/friends - Sheet1.csv")

In [35]:
df

,Unnamed: 0,fname,lname,age_sex,section,height(cm),weight(kg),age,spend_A,spend_B,spend_C
0,0,Rahul,Pandey,37_M,B,175.4,85.6,37,1500.0,200.0,300
1,1,Rakesh,Kumar,38_M,B,NaN,xx,38,NaN,1000.0,NaN
2,2,Nitesh,Mondol,35_M,B,165.1,?,35,500.0,-100.0,200
3,3,Arvind,Dwivedi,40_M,A,0,55.6,40,300.0,300.0,NaN
4,4,Nikhil,Shikharwar,39_M,B,160.8,160,39,200.0,NaN,300
5,5,Ashutosh,Merothiya,36_M,A,xx,-60,36,100.0,400.0,NaN
6,6,Shubhro,Das,35_M,C,170.3,75.5,35,NaN,500.0,500
7,7,Suvendu,Das,34_M,C,155.1,56.8,34,1000.0,100.0,xx
8,8,Swadesh,Kumar,36_M,C,154.2,60.6,36,100.0,200.0,300
9,9,Arun,Vishwakarma,38_M,A,162.1,58.7,38,600.0,200.0,200

In [27]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10 entries, 0 to 9
Data columns (total 11 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   Unnamed: 0  10 non-null     int64
 1   fname       10 non-null     object
 2   lname       10 non-null     object
 3   age_sex     10 non-null     object
 4   section     10 non-null     object
 5   height(cm)  9 non-null      object
 6   weight(kg)  10 non-null     object
 7   age         10 non-null     int64
 8   spend_A     8 non-null      float64
 9   spend_B     9 non-null      float64
 10  spend_C     7 non-null      object
dtypes: float64(2), int64(2), object(7)
memory usage: 1008.0+ bytes

## Changing the string "XX" value to NaN

In [36]:
df['height(cm)']=df['height(cm)'].apply(lambda x:"NaN" if x=="xx" else x)

In [37]:
df

,Unnamed: 0,fname,lname,age_sex,section,height(cm),weight(kg),age,spend_A,spend_B,spend_C
0,0,Rahul,Pandey,37_M,B,175.4,85.6,37,1500.0,200.0,300
1,1,Rakesh,Kumar,38_M,B,NaN,xx,38,NaN,1000.0,NaN
2,2,Nitesh,Mondol,35_M,B,165.1,?,35,500.0,-100.0,200
3,3,Arvind,Dwivedi,40_M,A,0,55.6,40,300.0,300.0,NaN
4,4,Nikhil,Shikharwar,39_M,B,160.8,160,39,200.0,NaN,300
5,5,Ashutosh,Merothiya,36_M,A,NaN,-60,36,100.0,400.0,NaN
6,6,Shubhro,Das,35_M,C,170.3,75.5,35,NaN,500.0,500
7,7,Suvendu,Das,34_M,C,155.1,56.8,34,1000.0,100.0,xx
8,8,Swadesh,Kumar,36_M,C,154.2,60.6,36,100.0,200.0,300
9,9,Arun,Vishwakarma,38_M,A,162.1,58.7,38,600.0,200.0,200

## spliting the age_sex column to age and sex columns

In [40]:
df[['age','sex']]=df['age_sex'].str.split('_',expand=True)

In [41]:
df

,Unnamed: 0,fname,lname,age_sex,section,height(cm),weight(kg),age,spend_A,spend_B,spend_C,sex
0,0,Rahul,Pandey,37_M,B,175.4,85.6,37,1500.0,200.0,300,M
1,1,Rakesh,Kumar,38_M,B,NaN,xx,38,NaN,1000.0,NaN,M
2,2,Nitesh,Mondol,35_M,B,165.1,?,35,500.0,-100.0,200,M
3,3,Arvind,Dwivedi,40_M,A,0,55.6,40,300.0,300.0,NaN,M
4,4,Nikhil,Shikharwar,39_M,B,160.8,160,39,200.0,NaN,300,M
5,5,Ashutosh,Merothiya,36_M,A,NaN,-60,36,100.0,400.0,NaN,M
6,6,Shubhro,Das,35_M,C,170.3,75.5,35,NaN,500.0,500,M
7,7,Suvendu,Das,34_M,C,155.1,56.8,34,1000.0,100.0,xx,M
8,8,Swadesh,Kumar,36_M,C,154.2,60.6,36,100.0,200.0,300,M
9,9,Arun,Vishwakarma,38_M,A,162.1,58.7,38,600.0,200.0,200,M

## Rearranging the columns

In [45]:
df.drop(['age_sex'], axis=1)

,Unnamed: 0,fname,lname,section,height(cm),weight(kg),age,spend_A,spend_B,spend_C,sex
0,0,Rahul,Pandey,B,175.4,85.6,37,1500.0,200.0,300,M
1,1,Rakesh,Kumar,B,NaN,xx,38,NaN,1000.0,NaN,M
2,2,Nitesh,Mondol,B,165.1,?,35,500.0,-100.0,200,M
3,3,Arvind,Dwivedi,A,0,55.6,40,300.0,300.0,NaN,M
4,4,Nikhil,Shikharwar,B,160.8,160,39,200.0,NaN,300,M
5,5,Ashutosh,Merothiya,A,NaN,-60,36,100.0,400.0,NaN,M
6,6,Shubhro,Das,C,170.3,75.5,35,NaN,500.0,500,M
7,7,Suvendu,Das,C,155.1,56.8,34,1000.0,100.0,xx,M
8,8,Swadesh,Kumar,C,154.2,60.6,36,100.0,200.0,300,M
9,9,Arun,Vishwakarma,A,162.1,58.7,38,600.0,200.0,200,M

In [47]:
df.loc[:,['fname','lname','section','age','sex','height(cm)','weight(kg)','spend_A','spend_B','spend_C']]

,fname,lname,section,age,sex,height(cm),weight(kg),spend_A,spend_B,spend_C
0,Rahul,Pandey,B,37,M,175.4,85.6,1500.0,200.0,300
1,Rakesh,Kumar,B,38,M,NaN,xx,NaN,1000.0,NaN
2,Nitesh,Mondol,B,35,M,165.1,?,500.0,-100.0,200
3,Arvind,Dwivedi,A,40,M,0,55.6,300.0,300.0,NaN
4,Nikhil,Shikharwar,B,39,M,160.8,160,200.0,NaN,300
5,Ashutosh,Merothiya,A,36,M,NaN,-60,100.0,400.0,NaN
6,Shubhro,Das,C,35,M,170.3,75.5,NaN,500.0,500
7,Suvendu,Das,C,34,M,155.1,56.8,1000.0,100.0,xx
8,Swadesh,Kumar,C,36,M,154.2,60.6,100.0,200.0,300
9,Arun,Vishwakarma,A,38,M,162.1,58.7,600.0,200.0,200